Script for copying built packages to the MSFS community folder
StevenFrost/SimCache pull request #18
Opened 2024-04-02 18:10 UTC by StevenFrost

2024-04-03 05:17 UTC, ollyau approved these changes

2024-04-03 07:31 UTC, HughesMDflyer4 requested changes
I get the following when running the script on my machine with only the Steam version installed: (full paths replaced with `<repo>`)

```
FINDSTR: Cannot open Flight
FINDSTR: Cannot open Simulator\UserCfg.opt
The syntax of the command is incorrect.

-------------------------------------------------------------------------------
   ROBOCOPY     ::     Robust File Copy for Windows
-------------------------------------------------------------------------------

  Started : Wednesday, April 3, 2024 12:20:51 AM
   Source : <repo>\Packages\Built\Packages\meridian-simcache\
     Dest : <repo>\Packages\=\Community\meridian-simcache \E\

    Files : *.*

  Options : *.* /DCOPY:DA /COPY:DAT /R:1000000 /W:30

------------------------------------------------------------------------------

                           2    <repo>\Packages\Built\Packages\meridian-simcache\

------------------------------------------------------------------------------

               Total    Copied   Skipped  Mismatch    FAILED    Extras
    Dirs :         1         0         1         0         0         0
   Files :         2         0         2         0         0         0
   Bytes :     1.6 k         0     1.6 k         0         0         0
   Times :   0:00:00   0:00:00                       0:00:00   0:00:00
   Ended : Wednesday, April 3, 2024 12:20:51 AM
```

2024-04-03 17:24 UTC, StevenFrost commented
Thanks for the log! Should be fixed in the latest version 👍

2024-04-03 23:47 UTC, ollyau approved these changes

2024-04-04 02:55 UTC, HughesMDflyer4 approved these changes
Works on my end now! Worth noting, if running the script when the package hasn't previously been copied to the Community folder, you'll get the following error:

`The system cannot find the file specified.`

I believe this is happening when rmdir tries to remove a directory that doesn't exist. Maybe worth adding a check for this in the future just to keep the error from happening?

2024-04-04 17:13 UTC, merged